version: '{build}'

pull_requests:
  do_not_increment_build_number: true

skip_tags: true
image: Visual Studio 2017

before_build:
- cmd: nuget restore

build:
  verbosity: minimal
  
test:
  assemblies:
    only:
      - Construktion.Tests.dll

test_script:
- cmd: dotnet test Construktion.Tests\Construktion.Tests.csproj